version: '3.7'
services:
  mysql:
    image: mysql:5.7.33
    restart: always
    ports:
      - 3306:3306
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: guest
      MYSQL_USER: guest
      MYSQL_PASSWORD: guest
    volumes:
      - ./mysql:/var/lib/mysql

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=guest
      - MONGO_INITDB_ROOT_PASSWORD=guest
      - MONGO_INITDB_DATABASE=guaitech-dev
    volumes:
      - ./mongodb/data/db:/data/db
    command: mongod --auth --logpath=/dev/null
