version: '3.7'
services:
  mysql:
    image: mysql:5.7.33
    restart: always
    ports:
      - 3306:3306
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: guest
      MYSQL_USER: guest
      MYSQL_PASSWORD: guest
    volumes:
      - ./mysql:/var/lib/mysql

